/* Learning packs. Add topics here: key -> {name, terms:{WORD:'short meaning'}}. Words: A-Z only, 4-9 letters. */
(function(root){
const P=(name,s)=>({name,terms:Object.fromEntries(s.split('|').map(x=>x.split(':')).map(([w,d])=>[w.trim(),d.trim()]))});
const T={
hr:P('HR','PAYROLL:Processing employee pay|ONBOARD:Welcome and integrate a new hire|BENEFITS:Perks beyond salary|APPRAISAL:Formal performance review|TRAINING:Teaching job skills|RETENTION:Keeping employees long term|TURNOVER:Rate staff leave and are replaced|HIRING:Filling a position|PROMOTION:Move to a higher role|GRIEVANCE:Formal employee complaint|MENTOR:Experienced guide for a colleague|CULTURE:Shared values and behaviors at work|ATTRITION:Gradual loss of staff|LEAVE:Approved time away from work|UNION:Group representing workers'),
recruitment:P('Recruitment','SOURCING:Actively finding candidates|CANDIDATE:Person applying for a role|SCREEN:Initial check of applicants|INTERVIEW:Structured conversation to assess fit|OFFER:Formal job proposal|REFERRAL:Candidate recommended by staff|PIPELINE:Pool of prospective hires|VACANCY:Open position|SHORTLIST:Best candidates after screening|TALENT:Skilled people you want to hire|RESUME:Summary of work history|REFERENCE:Previous employer feedback|HEADHUNT:Recruit senior people directly|ASSESS:Evaluate skills or fit'),
claude:P('Claude','CLAUDE:Anthropic AI assistant|PROMPT:Instruction you give the AI|TOKEN:Small chunk of text a model reads|CONTEXT:Information the model can see|ARTIFACT:Standalone output like a page or doc|SONNET:Balanced Claude model tier|OPUS:Most capable Claude model tier|HAIKU:Fast lightweight Claude model|SYSTEM:Background instructions for the AI|MODEL:Trained AI that generates answers|SAFETY:Making AI helpful and harmless|VISION:Ability to read images|MEMORY:Remembering details across chats|PROJECT:Workspace with shared files|AGENT:AI that takes actions on tasks|TOOLS:Functions the AI can call'),
copilot:P('Copilot','COPILOT:Microsoft AI assistant|PROMPT:Instruction you give the AI|DRAFT:First version created by AI|SUMMARIZE:Condense long content|EXCEL:Spreadsheet app Copilot can analyze|TEAMS:Chat and meeting app|OUTLOOK:Email app Copilot can draft in|DESIGNER:Tool for creating images and layouts|STUDIO:Builder for custom copilots|PLUGIN:Add-on that extends abilities|AGENT:AI that completes tasks for you|GROUNDING:Anchoring answers in your data|WORKSPACE:Place where you collaborate|NOTEBOOK:Space to collect notes and sources|RECAP:Short summary of a meeting'),
analytics:P('Business Analytics','DASHBOARD:Visual summary of key numbers|METRIC:Measurable value of performance|FORECAST:Prediction of future results|TREND:General direction of data over time|COHORT:Group sharing a characteristic|CHURN:Rate customers leave|MEDIAN:Middle value of a dataset|VARIANCE:How spread out values are|OUTLIER:Value far from the rest|SEGMENT:Subgroup of customers|FUNNEL:Steps from visitor to buyer|INSIGHT:Useful finding from data|PIVOT:Table that regroups data|QUERY:Request for data|SAMPLE:Subset used to study a group|MARGIN:Profit as share of revenue|REVENUE:Income from sales|BASELINE:Starting point for comparison'),
finance:P('Finance','BUDGET:Plan for income and spending|ASSET:Something of value owned|LIABILITY:Debt or obligation owed|EQUITY:Ownership value in a company|DIVIDEND:Profit paid to shareholders|LEDGER:Book of financial accounts|AUDIT:Independent check of records|CASHFLOW:Money moving in and out|INTEREST:Cost of borrowing money|INVOICE:Bill for goods or services|PROFIT:Revenue minus costs|ACCRUAL:Recording items when earned|HEDGE:Reduce risk of loss|YIELD:Return on an investment|CAPITAL:Money used to run or grow a business'),
projects:P('Project Management','SCOPE:What a project will deliver|SPRINT:Short fixed work cycle|BACKLOG:List of work still to do|MILESTONE:Key checkpoint|RISK:Chance of a problem|AGILE:Iterative way of working|GANTT:Timeline bar chart|DEADLINE:Date work is due|CHARTER:Document authorizing a project|KANBAN:Board showing work stages|TASK:Single unit of work|DELIVER:Hand over finished work|SCRUM:Framework built on sprints|ESCALATE:Raise an issue to leadership'),
marketing:P('Marketing','BRAND:Identity customers recognize|CAMPAIGN:Coordinated promotion effort|AUDIENCE:People you want to reach|LEADS:Potential customers|ORGANIC:Unpaid reach|REACH:People who saw your content|ENGAGE:Interact with content|NICHE:Specialized market|PERSONA:Profile of an ideal customer|SLOGAN:Short memorable phrase|POSITION:How a brand is perceived|CONVERT:Turn a prospect into a customer|COPY:Written marketing text'),
ai:P('AI and Machine Learning','NEURAL:Brain-inspired network type|DATASET:Collection of data for learning|BIAS:Unfair skew in results|FEATURE:Input variable for a model|LABEL:Correct answer attached to data|INFERENCE:Using a trained model|EMBEDDING:Numeric form of meaning|LEARNING:Improving from data|ALGORITHM:Step-by-step procedure|PARAMETER:Value a model learns|OVERFIT:Too tailored to training data|CLASSIFY:Assign items to categories|MODEL:Trained system that makes predictions'),
security:P('Cybersecurity','PHISHING:Fake messages that steal info|MALWARE:Harmful software|FIREWALL:Blocks unwanted network traffic|PASSWORD:Secret used to log in|ENCRYPT:Scramble data to protect it|BREACH:Unauthorized access to data|PATCH:Update that fixes a flaw|VIRUS:Self-copying malicious program|VAULT:Secure storage for secrets|ACCESS:Permission to use a resource|THREAT:Potential source of harm|BACKUP:Spare copy of data|SPOOF:Disguise as a trusted source|RANSOM:Payment demanded to restore data'),
excel:P('Excel','FORMULA:Calculation typed into a cell|WORKBOOK:File containing sheets|WORKSHEET:Single sheet of cells|VLOOKUP:Find a value in a table|CELL:Single box in the grid|COLUMN:Vertical line of cells|CHART:Visual graph of data|FILTER:Show only matching rows|SORT:Put data in order|MACRO:Recorded automated steps|RANGE:Group of cells|AVERAGE:Sum divided by count|SUMIF:Add cells meeting a rule|FREEZE:Keep rows visible while scrolling'),
leadership:P('Leadership','COACH:Develop others through guidance|DELEGATE:Hand tasks to others|FEEDBACK:Information on performance|TRUST:Confidence in others|EMPATHY:Understanding how others feel|INSPIRE:Motivate people|INTEGRITY:Honest, consistent principles|STRATEGY:Long-term plan to win|DECISION:Choice after weighing options|MORALE:Team confidence and spirit|CLARITY:Making expectations clear|ALIGN:Get everyone pulling the same way|VISION:Picture of the desired future'),
sales:P('Sales','PROSPECT:Potential buyer|QUOTA:Sales target|PITCH:Persuasive presentation|CLOSING:Securing the deal|UPSELL:Offer a pricier version|DISCOUNT:Price reduction|NEGOTIATE:Bargain to reach agreement|OBJECTION:Buyer concern or pushback|FOLLOWUP:Contact after a first meeting|DEMO:Product showcase|CLIENT:Customer you serve|RENEWAL:Extending a contract|TERRITORY:Assigned sales region|PIPELINE:Deals at each stage')};
root.WMX=root.WMX||{};root.WMX.TOPICS=T;if(typeof module==='object')module.exports=T;
})(typeof window!=='undefined'?window:globalThis);
